/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX
 * @brief     System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>

/* 如果仍然有问题，可以直接定义 NULL */
#ifndef NULL
#define NULL ((void*)0)
#endif

/* 如果仍然有问题，可以直接定义 ptrdiff_t */
#ifndef _PTRDIFF_T_DEFINED
#define _PTRDIFF_T_DEFINED
typedef long ptrdiff_t;
#endif

/* 添加导出符号声明 */
#define SYMBOL_EXPORT __attribute__((used, visibility("default")))

/* 全局变量，确保不被优化 */
SYMBOL_EXPORT void *__real_sbrk(ptrdiff_t incr);

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * 本实现从 '_end' 连接器符号开始分配
 * '_Min_Stack_Size' 连接器符号为MSP栈保留内存
 * 实现将 '_estack' 连接器符号视为RAM的结束
 * 注意：如果在执行过程中的任何时候，MSP栈的大小超过保留的大小，请增加 '_Min_Stack_Size'。
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */

/* 确保函数名称正确，并且不被优化掉 */
void *_sbrk(ptrdiff_t incr) __attribute__((used)); 
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t _end; /* 连接器符号定义在链接器脚本中 */
  extern uint8_t _estack; /* 连接器符号定义在链接器脚本中 */
  extern uint32_t _Min_Stack_Size; /* 连接器符号定义在链接器脚本中 */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;
  const uint8_t *max_heap = (uint8_t *)stack_limit;
  uint8_t *prev_heap_end;

  /* 在第一次调用时初始化堆结束 */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  /* 保护堆不被MSP栈占用 */
  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}
